#!/usr/bin/env python3
"""Tests for the signed update chain.

The update path used to certify itself: the release endpoint returned a download URL
and the digest of what it pointed at in the same body, and manifest.json declared the
digests of the files shipped beside it. Both checks pass for a package an attacker
built. Every assertion here corresponds to a way that gap could be reopened -- by
trusting a field the signature never covered, by accepting a package whose signature
is absent, by letting malformed input fall through a raise into a caller's generic
`except`, or by talking the verifier into a different algorithm.

The keys are real Ed25519 keys generated by openssl in a temp directory, and the
signatures are real signatures. Nothing is stubbed: the primitive is a subprocess, so
mocking it out would test only the wrapper.

Run with:  python -m unittest test_update_signature
"""

import base64
import json
import os
import shutil
import subprocess
import tempfile
import unittest
from unittest import mock

import check_updates
import create_upgrade_zip
import helios_sig

HERE = os.path.dirname(os.path.abspath(__file__))

KEY_DIR = None
RELEASE_KEY = None
RELEASE_PUB = None
ATTACKER_KEY = None
ATTACKER_PUB = None


def _openssl(args):
    return subprocess.run(
        ["openssl"] + args,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def _make_keypair(directory, name, algorithm="ed25519"):
    private_path = os.path.join(directory, name + ".key")
    public_path = os.path.join(directory, name + ".pub")
    args = ["genpkey", "-algorithm", algorithm, "-out", private_path]
    if algorithm.upper() == "RSA":
        args += ["-pkeyopt", "rsa_keygen_bits:2048"]
    if _openssl(args).returncode != 0:
        raise unittest.SkipTest(f"openssl cannot generate an {algorithm} key")
    if _openssl(["pkey", "-in", private_path, "-pubout", "-out", public_path]).returncode != 0:
        raise unittest.SkipTest(f"openssl cannot export an {algorithm} public key")
    return private_path, public_path


def setUpModule():
    """Two keypairs: the release key, and one standing in for anybody else's."""
    global KEY_DIR, RELEASE_KEY, RELEASE_PUB, ATTACKER_KEY, ATTACKER_PUB
    KEY_DIR = tempfile.mkdtemp(prefix="helios-sig-tests-")
    try:
        RELEASE_KEY, RELEASE_PUB = _make_keypair(KEY_DIR, "release")
        ATTACKER_KEY, ATTACKER_PUB = _make_keypair(KEY_DIR, "attacker")
    except (unittest.SkipTest, OSError):
        shutil.rmtree(KEY_DIR, ignore_errors=True)
        raise unittest.SkipTest("openssl with Ed25519 support (1.1.1+) is required")


def tearDownModule():
    if KEY_DIR:
        shutil.rmtree(KEY_DIR, ignore_errors=True)


def signed_release(payload, key=None):
    """A release response as create_upgrade_zip.py publishes it."""
    return helios_sig.build_signed_document(payload, key or RELEASE_KEY)


SAMPLE_RELEASE = {
    "latest_version": "9.9.9-test",
    "release_date": "2026-01-01",
    "download_url": "https://updates-helios.zerotwo.cloud/downloads/upgrade_9.9.9-test.zip",
    "sha256": "a" * 64,
    "size": 4096,
    "changelog": "# 9.9.9-test",
    "components": {"hylia": "9.9.9-test"},
}


class DetachedSignatureTests(unittest.TestCase):
    """verify_detached_signature: the primitive everything else rests on."""

    def test_a_signature_from_the_pinned_key_verifies(self):
        payload = b'{"build": "9.9.9-test"}'
        envelope = helios_sig.sign_bytes(payload, RELEASE_KEY)
        key_id = helios_sig.verify_detached_signature(payload, envelope, RELEASE_PUB)
        self.assertEqual(key_id, helios_sig.key_fingerprint(RELEASE_PUB))

    def test_one_flipped_byte_in_the_payload_is_rejected(self):
        payload = b'{"build": "9.9.9-test"}'
        envelope = helios_sig.sign_bytes(payload, RELEASE_KEY)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_detached_signature(payload.replace(b"9.9.9", b"9.9.8"), envelope, RELEASE_PUB)

    def test_a_signature_from_another_key_is_rejected(self):
        # The property an HMAC could not give us: holding a verifier does not make you
        # a signer, so a compromised node cannot mint a release for the fleet.
        payload = b"release"
        envelope = helios_sig.sign_bytes(payload, ATTACKER_KEY)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_detached_signature(payload, envelope, RELEASE_PUB)

    def test_a_wrong_key_failure_names_both_key_ids(self):
        # A rotated release key and a tampered package look identical otherwise, and an
        # operator who cannot tell them apart reaches for the escape hatch.
        payload = b"release"
        envelope = helios_sig.sign_bytes(payload, ATTACKER_KEY)
        with self.assertRaises(helios_sig.SignatureError) as caught:
            helios_sig.verify_detached_signature(payload, envelope, RELEASE_PUB)
        message = str(caught.exception)
        self.assertIn(helios_sig.key_fingerprint(ATTACKER_KEY, private=True), message)
        self.assertIn(helios_sig.key_fingerprint(RELEASE_PUB), message)

    def test_absent_signature_is_reported_as_missing_not_as_bad(self):
        # The two cases are handled differently by every caller, so they must not
        # collapse into one exception type -- while a caller that does not care about
        # the distinction still catches SignatureError and still fails closed.
        for envelope in (None, "   "):
            with self.subTest(envelope=envelope):
                with self.assertRaises(helios_sig.SignatureError) as caught:
                    helios_sig.verify_detached_signature(b"release", envelope, RELEASE_PUB)
                self.assertIsInstance(caught.exception, helios_sig.SignatureMissing)

    def test_malformed_envelopes_are_refused_rather_than_raised(self):
        """Every one of these arrives from the network. A ValueError out of base64 or
        json escapes a caller that is only catching SignatureError."""
        good = helios_sig.sign_bytes(b"release", RELEASE_KEY)
        cases = {
            "not json at all": "}{",
            "a bare string": '"signature"',
            "a json list": "[]",
            "no signature field": {"algorithm": "ed25519"},
            "signature is not a string": {"algorithm": "ed25519", "signature": 1234},
            "signature is not base64": {"algorithm": "ed25519", "signature": "not base64!!"},
            "signature is empty": {"algorithm": "ed25519", "signature": ""},
            "signature is truncated": {
                "algorithm": "ed25519",
                "signature": base64.b64encode(b"\x00" * 63).decode("ascii"),
            },
            "signature is overlong": {
                "algorithm": "ed25519",
                "signature": base64.b64encode(b"\x00" * 65).decode("ascii"),
            },
            "no algorithm": {"signature": good["signature"]},
            "algorithm is not a string": {"algorithm": ["ed25519"], "signature": good["signature"]},
            "key_id carries a quote": {
                "algorithm": "ed25519",
                "key_id": "abc' OR '1'='1",
                "signature": good["signature"],
            },
            "invalid utf-8": b"\xff\xfe not utf-8",
        }
        for name, envelope in cases.items():
            with self.subTest(envelope=name):
                with self.assertRaises(helios_sig.SignatureError):
                    helios_sig.verify_detached_signature(b"release", envelope, RELEASE_PUB)

    def test_a_different_algorithm_is_refused_even_with_a_valid_signature(self):
        # Algorithm confusion is how a signature check gets defeated without anyone
        # breaking a signature: the envelope names something the verifier handles more
        # leniently and the check quietly becomes a formality.
        envelope = helios_sig.sign_bytes(b"release", RELEASE_KEY)
        envelope["algorithm"] = "hmac-sha256"
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_detached_signature(b"release", envelope, RELEASE_PUB)

    def test_payload_must_be_bytes(self):
        # A str payload would be encoded implicitly somewhere, and the bytes that were
        # signed would stop being the bytes that are checked.
        envelope = helios_sig.sign_bytes(b"release", RELEASE_KEY)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_detached_signature("release", envelope, RELEASE_PUB)


class PinnedKeyTests(unittest.TestCase):
    """The key has to be pinned, and it has to be the key we think it is."""

    def test_no_pinned_key_means_no_verification(self):
        envelope = helios_sig.sign_bytes(b"release", RELEASE_KEY)
        absent = os.path.join(KEY_DIR, "does-not-exist.pub")
        with self.assertRaises(helios_sig.SignatureError) as caught:
            helios_sig.verify_detached_signature(b"release", envelope, absent)
        self.assertIn(absent, str(caught.exception))

    def test_a_pinned_key_of_the_wrong_algorithm_says_so(self):
        # Pinning an RSA key by mistake otherwise produces an opaque provider error on
        # every release, which reads exactly like an attack.
        _, rsa_pub = _make_keypair(KEY_DIR, "wrong-algorithm", algorithm="RSA")
        envelope = helios_sig.sign_bytes(b"release", RELEASE_KEY)
        with self.assertRaises(helios_sig.SignatureError) as caught:
            helios_sig.verify_detached_signature(b"release", envelope, rsa_pub)
        self.assertIn("Ed25519", str(caught.exception))

    def test_a_garbage_pinned_key_is_refused(self):
        junk = os.path.join(KEY_DIR, "junk.pub")
        with open(junk, "w", encoding="utf-8") as handle:
            handle.write("-----BEGIN PUBLIC KEY-----\nnope\n-----END PUBLIC KEY-----\n")
        envelope = helios_sig.sign_bytes(b"release", RELEASE_KEY)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_detached_signature(b"release", envelope, junk)


class PackageManifestTests(unittest.TestCase):
    """verify_package_manifest over an extracted update package."""

    def setUp(self):
        self.extract_dir = tempfile.mkdtemp(prefix="helios-pkg-")
        self.manifest_path = os.path.join(self.extract_dir, helios_sig.MANIFEST_FILENAME)
        self.manifest = {
            "build": "9.9.9-test",
            "components": {
                "hylia": {
                    "file": "hylia",
                    "sha256": "b" * 64,
                    "target_path": "/usr/local/bin/hylia",
                    "version": "9.9.9-test",
                }
            },
        }
        self.write_manifest(self.manifest)

    def tearDown(self):
        shutil.rmtree(self.extract_dir, ignore_errors=True)

    def write_manifest(self, manifest):
        with open(self.manifest_path, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(manifest, handle, indent=2)

    def sign(self, key=None):
        helios_sig.sign_manifest_file(self.manifest_path, key or RELEASE_KEY)

    def test_a_signed_manifest_verifies(self):
        self.sign()
        self.assertEqual(
            helios_sig.verify_package_manifest(self.extract_dir, RELEASE_PUB),
            helios_sig.key_fingerprint(RELEASE_PUB),
        )

    def test_a_swapped_component_digest_is_rejected(self):
        # The attack the per-component digests could never catch: replace a file and
        # rewrite the digest that describes it. Both halves of the package still agree.
        self.sign()
        tampered = json.loads(json.dumps(self.manifest))
        tampered["components"]["hylia"]["sha256"] = "c" * 64
        self.write_manifest(tampered)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_package_manifest(self.extract_dir, RELEASE_PUB)

    def test_an_added_component_is_rejected(self):
        # Appending an entry installs an extra file at an attacker-chosen path on every
        # node. Nothing but a signature over the whole manifest notices.
        self.sign()
        tampered = json.loads(json.dumps(self.manifest))
        tampered["components"]["backdoor"] = {
            "file": "backdoor",
            "sha256": "d" * 64,
            "target_path": "/usr/local/bin/backdoor",
            "version": "9.9.9-test",
        }
        self.write_manifest(tampered)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_package_manifest(self.extract_dir, RELEASE_PUB)

    def test_a_manifest_signed_by_another_key_is_rejected(self):
        self.sign(ATTACKER_KEY)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_package_manifest(self.extract_dir, RELEASE_PUB)

    def test_a_package_with_no_signature_is_missing_not_malformed(self):
        with self.assertRaises(helios_sig.SignatureMissing):
            helios_sig.verify_package_manifest(self.extract_dir, RELEASE_PUB)

    def test_a_package_with_no_manifest_is_an_error(self):
        self.sign()
        os.remove(self.manifest_path)
        with self.assertRaises(helios_sig.SignatureError) as caught:
            helios_sig.verify_package_manifest(self.extract_dir, RELEASE_PUB)
        # Nothing to verify is not the same as nothing having signed it: a package with
        # no manifest must not land in the transition allowance for unsigned ones.
        self.assertNotIsInstance(caught.exception, helios_sig.SignatureMissing)

    def test_an_empty_signature_file_is_refused(self):
        with open(os.path.join(self.extract_dir, helios_sig.MANIFEST_SIGNATURE_FILENAME), "w") as handle:
            handle.write("")
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_package_manifest(self.extract_dir, RELEASE_PUB)


class ReleaseDocumentTests(unittest.TestCase):
    """verify_signed_document: what the release endpoint returns."""

    def test_the_signed_payload_comes_back_intact(self):
        document = signed_release(SAMPLE_RELEASE)
        release, key_id = helios_sig.verify_signed_document(document, RELEASE_PUB)
        self.assertEqual(release, SAMPLE_RELEASE)
        self.assertEqual(key_id, helios_sig.key_fingerprint(RELEASE_PUB))

    def test_editing_the_signed_text_is_rejected(self):
        document = signed_release(SAMPLE_RELEASE)
        document["signed"] = document["signed"].replace(
            "updates-helios.zerotwo.cloud", "updates-helios.zerotw0.cloud")
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_signed_document(document, RELEASE_PUB)

    def test_a_response_signed_by_another_key_is_rejected(self):
        document = signed_release(SAMPLE_RELEASE, ATTACKER_KEY)
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_signed_document(document, RELEASE_PUB)

    def test_signed_sent_as_an_object_is_rejected(self):
        # Re-serialising a parsed object to check it would put a JSON encoder between
        # the bytes that were signed and the bytes that are verified.
        document = signed_release(SAMPLE_RELEASE)
        document["signed"] = SAMPLE_RELEASE
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_signed_document(document, RELEASE_PUB)

    def test_a_signature_with_nothing_signed_is_an_error(self):
        document = signed_release(SAMPLE_RELEASE)
        del document["signed"]
        with self.assertRaises(helios_sig.SignatureError):
            helios_sig.verify_signed_document(document, RELEASE_PUB)

    def test_the_legacy_unsigned_response_is_reported_as_missing(self):
        with self.assertRaises(helios_sig.SignatureMissing):
            helios_sig.verify_signed_document(dict(SAMPLE_RELEASE), RELEASE_PUB)


class CheckUpdatesResolutionTests(unittest.TestCase):
    """check_updates.resolve_release_document: the fix for the original defect."""

    def test_fields_are_read_from_the_signed_half_only(self):
        # The defect in one test: the response carries its own download_url and sha256
        # beside the signed ones. Taking either of them back is the whole bug returning,
        # this time with a valid signature elsewhere in the body to vouch for it.
        document = signed_release(SAMPLE_RELEASE)
        document["download_url"] = "https://attacker.example/upgrade.zip"
        document["sha256"] = "e" * 64
        document["latest_version"] = "6.6.6-evil"

        release, note = check_updates.resolve_release_document(document, RELEASE_PUB)
        self.assertEqual(note, "")
        self.assertEqual(release["download_url"], SAMPLE_RELEASE["download_url"])
        self.assertEqual(release["sha256"], SAMPLE_RELEASE["sha256"])
        self.assertEqual(release["latest_version"], SAMPLE_RELEASE["latest_version"])

    def test_an_unsigned_release_is_refused_and_says_how_to_proceed(self):
        with mock.patch.dict(os.environ, {}, clear=False):
            os.environ.pop(helios_sig.UNSIGNED_OVERRIDE_ENV, None)
            with self.assertRaises(Exception) as caught:
                check_updates.resolve_release_document(dict(SAMPLE_RELEASE), RELEASE_PUB)
        message = str(caught.exception)
        self.assertIn("Refusing this release", message)
        self.assertIn(helios_sig.UNSIGNED_OVERRIDE_ENV, message)

    def test_a_bad_signature_is_refused_even_with_the_escape_hatch_set(self):
        # The escape hatch covers a release server that has not been re-signed yet. A
        # signature that is present and wrong is an attack in any migration state.
        document = signed_release(SAMPLE_RELEASE, ATTACKER_KEY)
        with mock.patch.dict(
            os.environ,
            {helios_sig.UNSIGNED_OVERRIDE_ENV: helios_sig.UNSIGNED_OVERRIDE_VALUE},
        ):
            with self.assertRaises(Exception) as caught:
                check_updates.resolve_release_document(document, RELEASE_PUB)
        self.assertIn("Refusing this release", str(caught.exception))

    def test_the_escape_hatch_accepts_an_unsigned_release_and_flags_it(self):
        with mock.patch.dict(
            os.environ,
            {helios_sig.UNSIGNED_OVERRIDE_ENV: helios_sig.UNSIGNED_OVERRIDE_VALUE},
        ):
            release, note = check_updates.resolve_release_document(dict(SAMPLE_RELEASE), RELEASE_PUB)
        self.assertEqual(release["download_url"], SAMPLE_RELEASE["download_url"])
        # The note lands in lcm_update_state.error_msg, which Spectrum shows on the LCM
        # page. An accepted-but-unverified release that looks identical to a verified
        # one is how a temporary migration setting becomes permanent.
        self.assertIn("UNVERIFIED", note)

    def test_the_escape_hatch_ignores_the_usual_truthy_values(self):
        for value in ("1", "true", "yes", "TRUE", ""):
            with self.subTest(value=value):
                with mock.patch.dict(os.environ, {helios_sig.UNSIGNED_OVERRIDE_ENV: value}):
                    with self.assertRaises(Exception):
                        check_updates.resolve_release_document(dict(SAMPLE_RELEASE), RELEASE_PUB)

    def test_a_missing_pinned_key_fails_the_check_rather_than_skipping_it(self):
        document = signed_release(SAMPLE_RELEASE)
        absent = os.path.join(KEY_DIR, "unpinned.pub")
        with self.assertRaises(Exception):
            check_updates.resolve_release_document(document, absent)


class PackageDigestValidationTests(unittest.TestCase):
    """check_updates.validate_package_digest, checked where the release can be named."""

    def test_a_hex_digest_is_accepted_and_lowercased(self):
        self.assertEqual(check_updates.validate_package_digest("A" * 64), "a" * 64)

    def test_anything_that_is_not_a_digest_is_refused(self):
        for value in (None, "", "not a digest", "a" * 63, "a" * 65, "g" * 64, 12345):
            with self.subTest(value=value):
                with self.assertRaises(Exception):
                    check_updates.validate_package_digest(value)


class BuildOutputTests(unittest.TestCase):
    """create_upgrade_zip.py's release document, verified the way a node verifies it."""

    def setUp(self):
        self.work_dir = tempfile.mkdtemp(prefix="helios-build-")
        self.previous_cwd = os.getcwd()
        os.chdir(self.work_dir)
        # write_release_document hashes the package it just built.
        with open(create_upgrade_zip.ZIP_NAME, "wb") as handle:
            handle.write(b"PK\x03\x04 not really a zip, but it has a digest")
        self.components = {"hylia": {"version": "9.9.9-test"}}

    def tearDown(self):
        os.chdir(self.previous_cwd)
        shutil.rmtree(self.work_dir, ignore_errors=True)

    def read_release_document(self):
        with open(create_upgrade_zip.RELEASE_DOC_NAME, "r", encoding="utf-8") as handle:
            return json.load(handle)

    def test_a_signed_build_verifies_against_the_pinned_key(self):
        digest = create_upgrade_zip.write_release_document(RELEASE_KEY, self.components, b"{}")
        release, _ = helios_sig.verify_signed_document(self.read_release_document(), RELEASE_PUB)
        # The digest a node downloads against is asserted by the signer, not observed by
        # the host that serves the file.
        self.assertEqual(release["sha256"], digest)
        self.assertEqual(release["download_url"], create_upgrade_zip.RELEASE_DOWNLOAD_URL)
        self.assertEqual(release["components"], {"hylia": "9.9.9-test"})
        self.assertEqual(release["latest_version"], create_upgrade_zip.VERSION)

    def test_the_published_document_survives_a_json_round_trip(self):
        # The signature covers the exact text in "signed". Writing the document with
        # json.dump and reading it back must not disturb those bytes.
        create_upgrade_zip.write_release_document(RELEASE_KEY, self.components, b"{}")
        reloaded = self.read_release_document()
        release, _ = check_updates.resolve_release_document(reloaded, RELEASE_PUB)
        self.assertEqual(release["latest_version"], create_upgrade_zip.VERSION)

    def test_an_unsigned_build_is_refused_by_check_updates(self):
        create_upgrade_zip.write_release_document(None, self.components, b"{}")
        document = self.read_release_document()
        self.assertNotIn("signature", document)
        with mock.patch.dict(os.environ, {}, clear=False):
            os.environ.pop(helios_sig.UNSIGNED_OVERRIDE_ENV, None)
            with self.assertRaises(Exception):
                check_updates.resolve_release_document(document, RELEASE_PUB)

    def test_building_without_a_key_refuses_rather_than_shipping_unsigned(self):
        absent = os.path.join(self.work_dir, "no-such.key")
        with mock.patch.dict(os.environ, {helios_sig.PRIVATE_KEY_ENV: absent}, clear=False):
            os.environ.pop(helios_sig.UNSIGNED_OVERRIDE_ENV, None)
            with self.assertRaises(SystemExit) as caught:
                create_upgrade_zip.resolve_signing_key()
        self.assertIn("openssl genpkey", str(caught.exception))

    def test_a_non_https_download_url_is_never_signed(self):
        with mock.patch.object(create_upgrade_zip, "RELEASE_DOWNLOAD_URL", "http://updates.example/u.zip"):
            with self.assertRaises(SystemExit):
                create_upgrade_zip.write_release_document(RELEASE_KEY, self.components, b"{}")


if __name__ == "__main__":
    unittest.main()
