defmodule SpectrumPhx.AccountsTest do
  use ExUnit.Case, async: true

  alias SpectrumPhx.Accounts

  describe "verify_password/2 against the Python tier's format" do
    # Generated by spectrum_server.py's hash_password("helios"). Both tiers must accept
    # the same stored hashes during migration, so this is pinned rather than regenerated.
    @python_hash "pbkdf2_sha256$100000$11ed63cf9affb9ed$Hb/nmU6t7h1BFkk/JgcCAeU0swm1MzTJv9MI0OJb3MY="

    test "accepts the correct password" do
      assert Accounts.verify_password("helios", @python_hash)
    end

    test "rejects a wrong password" do
      refute Accounts.verify_password("wrong", @python_hash)
    end

    test "rejects an empty password" do
      refute Accounts.verify_password("", @python_hash)
    end

    test "rejects a hash with a mangled digest" do
      refute Accounts.verify_password("helios", String.replace(@python_hash, "Hb/", "XX/"))
    end

    test "rejects malformed encodings rather than raising" do
      for bad <- [
            "",
            "garbage",
            "pbkdf2_sha256$100000",
            "$$$",
            "md5$1$a$b",
            "pbkdf2_sha256$notanumber$salt$digest",
            "pbkdf2_sha256$0$salt$digest"
          ] do
        refute Accounts.verify_password("helios", bad), "should reject #{inspect(bad)}"
      end
    end

    test "rejects non-binary input" do
      refute Accounts.verify_password(nil, @python_hash)
      refute Accounts.verify_password("helios", nil)
    end
  end

  describe "hash_password/1" do
    test "round-trips with verify_password/2" do
      hash = Accounts.hash_password("correct horse")
      assert Accounts.verify_password("correct horse", hash)
      refute Accounts.verify_password("Correct horse", hash)
    end

    test "produces the format the Python tier parses" do
      assert ["pbkdf2_sha256", iterations, salt, digest] =
               String.split(Accounts.hash_password("x"), "$")

      assert {100_000, ""} = Integer.parse(iterations)
      assert String.match?(salt, ~r/\A[0-9a-f]{16}\z/)
      assert {:ok, raw} = Base.decode64(digest)
      assert byte_size(raw) == 32
    end

    test "salts, so the same password hashes differently each time" do
      refute Accounts.hash_password("same") == Accounts.hash_password("same")
    end
  end

  describe "valid_token_format?/1" do
    test "accepts a token of the shape create_session/1 generates" do
      assert Accounts.valid_token_format?(String.duplicate("a", 64))
      assert Accounts.valid_token_format?(String.duplicate("0f", 32))
    end

    test "rejects anything else" do
      # This guard is what keeps an attacker-supplied token out of a query. The Python
      # tier concatenated it straight into CQL from a header, cookie or query parameter.
      for bad <- [
            "",
            "abc",
            String.duplicate("a", 63),
            String.duplicate("a", 65),
            String.duplicate("A", 64),
            String.duplicate("g", 64),
            "' OR 1=1--",
            "a' UNION SELECT username FROM hydra.users; --",
            String.duplicate("a", 32) <> "; DROP TABLE hydra.sessions;",
            "../../etc/passwd",
            String.duplicate("a", 63) <> "\n"
          ] do
        refute Accounts.valid_token_format?(bad), "should reject #{inspect(bad)}"
      end
    end

    test "rejects non-binary input" do
      refute Accounts.valid_token_format?(nil)
      refute Accounts.valid_token_format?(12_345)
    end
  end

  describe "user_from_token/1" do
    test "refuses a malformed token without reaching the database" do
      # No database is configured in test; a malformed token must be rejected before any
      # query is attempted, so this returns rather than erroring on a connection.
      assert {:error, :malformed_token} = Accounts.user_from_token("' OR 1=1--")
      assert {:error, :malformed_token} = Accounts.user_from_token(nil)
    end
  end

  describe "authenticate/2" do
    test "rejects non-binary credentials" do
      assert {:error, :invalid_credentials} = Accounts.authenticate(nil, "x")
      assert {:error, :invalid_credentials} = Accounts.authenticate("x", nil)
    end
  end
end
